from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsAngleWaveEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamWaveEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamWaveDistanceEnv

from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsAngleLineEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamLineEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamLineDistanceEnv

from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsAngleZigzagEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamZigzagEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamZigzagDistanceEnv

from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsAngleCircleEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamCircleEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamCircleDistanceEnv


from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsAngleRandomEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamRandomEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamRandomDistanceEnv

from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsAngleCursorEnv
from gym_mujoco_planar_snake.envs.mujoco_15.mujoco_planar_snake_cars_cam import MujocoPlanarSnakeCarsCamCursorEnv



